name: CI/CD Pipeline for Frontend

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        DOCKER_VERSION=$(git rev-parse --short HEAD)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/appointments:${DOCKER_VERSION} ./frontend
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${DOCKER_VERSION}
