name: CI/CD Pipeline for Appointments

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        DOCKER_VERSION=$(git rev-parse --short HEAD)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/appointments:${DOCKER_VERSION} .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/appointments:${DOCKER_VERSION}

    - name: Path based filtering
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'appointments/'; then
          echo "Changes in appointments folder. Triggering build..."
        else
          echo "No changes in appointments folder. Skipping build."
          exit 1
        fi
